name: Build and Public Excalidraw Tauri Application

on:
  push:
    tags:
      - "app-v*" # only build it when add app-v* tag
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest] # [macos-latest, windows-latest, ubuntu-latest]
      fail-fast: false  # true: (or its expression evaluates to true) GitHub will cancel all in-progress and queued jobs in the matrix if any job in the matrix fails. 
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
    
      - name: Enable Corepack # for yarn version error
        run: corepack enable

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies  # working-directory: excalidraw-app
        run: yarn install

      - name: Build front-end  # working-directory: excalidraw-app
        run: yarn workspace excalidraw-app build
        env:
          VERCEL_GIT_COMMIT_SHA: ${{ github.sha }} # set env paramater

      - name: Build and Publish Tauri app
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: excalidraw-app
          tagName: ${{ github.ref_name }} # v${{ github.run_number }}
          releaseName: "Release ${{ github.ref_name }}" # "Release v${{ github.run_number }}"
          releaseBody: "Auto build for ${{ github.ref_name }}"
          releaseDraft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_GIT_COMMIT_SHA: ${{ github.sha }} # set env paramater
